### ISSUE TITLE
Update AWS SDK to v2

### ISSUE THREAD

**Issue by jshlbrd** [brexhq/substation#116]
**Is your feature request related to a problem? Please describe.**
The project is using the stable but outdated AWS SDK and should be upgraded to v2.

**Describe the solution you'd like**
[Upgrade all AWS packages to v2](https://aws.github.io/aws-sdk-go-v2/docs/migrating/) and [refactor unit tests](https://aws.github.io/aws-sdk-go-v2/docs/unit-testing/). This will [have an impact on X-Ray support](https://github.com/aws/aws-xray-sdk-go/issues/277#issuecomment-1150470625) that should be addressed as well. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AshutoshNanaware** [comment]
Hello @jshlbrd , I can work on this. Can you please assign this to me?
