### ISSUE TITLE
Parquet Writer Support

### ISSUE THREAD

**Issue by jshlbrd** [brexhq/substation#118]
**Is your feature request related to a problem? Please describe.**
The project team has received asks about Parquet support over the past few months. We don't have a need for Parquet internally, but if someone else is interested in adding it, then it's worth adding.

**Describe the solution you'd like**
This should be added in the [Sink file wrapper](https://github.com/brexhq/substation/blob/main/internal/sink/sink.go#L95). I'm not very opinionated about supporting custom options aside from custom compression settings.

**Describe alternatives you've considered**
N/A

**Additional context**
There are multiple implementations of Parquet in Go, but all have positives and negatives. [parquet-go](https://github.com/segmentio/parquet-go) appears to have the most development velocity, but would be complex to implement ([the code in Benthos](https://github.com/benthosdev/benthos/issues/1855) is a good model).

**Comment by Bin-security** [comment]
Thanks @jshlbrd This is a very useful feature. Parquet and other columnar formats can increase query performance and efficiency once logs are loaded by query engines.

**Comment by jshlbrd** [comment]
Closing this -- if anyone wants Parquet support, then they could try using AWS Glue to convert from JSON, otherwise a Python script would likely suffice. If support did exist, then Substation would [likely produce many small files which can cause problems](https://medium.com/bigspark/compaction-merge-of-small-parquet-files-bef60847e60b). We wouldn't want to add this without some large scale testing.
