### ISSUE TITLE
Verkada has adopted Substation!

### ISSUE THREAD

**Issue by chencaoverkada** [brexhq/substation#231]
### Organization Name

Verkada

### Organization Website

https://www.verkada.com/

### Stage of Adoption

We're using Substation in production

### Description of Use

Substation is used to enrich and normalize **all** of Verkada's logging pipelines. It has also helped Verkada on log filtering before the logs are ingested into our in house SIEM.

**Comment by jshlbrd** [comment]
Thanks @chencaoverkada, this was added to the adopters file!
