### ISSUE TITLE
Substation Playground

### ISSUE THREAD

**Issue by brittonhayes** [brexhq/substation#259]
**Is your feature request related to a problem? Please describe.**

The previous substation playground implementation faced challenges with ease of maintenance and WASM compatibility. Specifically:
- Specifying transforms as non-WASM compatible with build constraints makes it difficult to maintain the same switch case structure
- There are concerns about users potentially using the hosted domain for outbound requests

**Describe the solution you'd like**

I suggest changing the playground to a locally-served application with the following features:
- Users can serve the playground locally using the command `substation playground`
- Remove WASM usage and replace it with an HTML form that submits configurations to a locally served HTTP endpoint
- This approach defers responsibility and risk to the user's device while still providing a learning and exploration environment

**Describe alternatives you've considered**

The current WASM-based approach was considered but proved challenging due to maintenance quirks, compatibility issues, and security concerns

**Additional context**

This solution offers several advantages:
- It avoids the constraints of WASM compatibility
- It's low maintenance as it's just an ingress point to run substation configurations on the user's device
- There's no need for hosting a site or owning a server

**Comment by jshlbrd** [comment]
I'm aligned on this, hosted WASM is nice but was painfully inadequate when attempted in earlier versions of Substation. Adding this to the CLI brings back the functionality with minimal overhead on the project maintainers. 👍
