### ISSUE TITLE
Tracking 2023 Roadmap

### ISSUE THREAD

**Issue by markofu** [brexhq/substation#52]
**Is your feature request related to a problem? Please describe.**
Depends, maybe not 🤷 

**Describe the solution you'd like**
It would be super helpful if we could track the features mentioned in the [2023 Roadmap](https://github.com/brexhq/substation/discussions/45) as "_Issues_" with tags such as "_enhancement_" 😄 

**Describe alternatives you've considered**
✍️ the issues/features etc down on 🧻  but that doesn't scale 🤔 

**Additional context**
n/a

**Comment by jshlbrd** [comment]
Used up all my 🧻 so I documented these as new issues!
