### ISSUE TITLE
Request-Reply Microservices / Remote Procedure Calls

### ISSUE THREAD

**Issue by jshlbrd** [brexhq/substation#54]
**Is your feature request related to a problem? Please describe.**

From [the 2023 roadmap](https://github.com/brexhq/substation/discussions/45), the system doesn't currently support request-response interactions which limit its use in distributed systems. For example, we may want to centralize capabilities by deploying Substation _as a node_ in a deployment where the node only performs one action (e.g., receive IP address, perform DNS resolution, return DNS results). 

**Describe the solution you'd like**

Add support for the following:
- AWS Lambda synchronous invocation
- gRPC unary RPC

**Describe alternatives you've considered**

It's possible to achieve something like this by implementing [the caching strategies described here](https://substation.readme.io/docs/caching-strategies), though that solution is much more complex than what is proposed here.

**Additional context**
N/A

**Comment by dnelson27** [comment]
I can take a stab at this one. I'll work on some protos for the transformers and a dummy implementation! I'll document my thoughts on the naming and the chosen functionality to expose in my PR!
